LOAD DATA
INFILE 'Datos_COVID.csv'
INSERT INTO TABLE Datos_COVID
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    ID_CASO,
    SEXO,
    ENTIDAD_RES,
    DEFUNCION,
    EDAD,
    DIABETES,
    EPOC,
    ASMA,
    HIPERTENSION,
    CARDIOVASCULAR,
    OBESIDAD,
    TABAQUISMO,
    CLASIFICACION
)